### ISSUE TITLE
I just run build-all

### ISSUE THREAD

**Issue by ycrxun** [parrot-translate/parrot#88]
For bugs or unexpected behaviors please use the following template:

## Expected Behavior

build and started.

## Actual Behavior
```shell
[soi@master parrot-translate]$ cd parrot/
[soi@master parrot]$ ./build/build-all.sh 
Installing web app dependencies, this might take a few minutes...

> node-sass@4.7.2 install /home/soi/golang/src/github.com/parrot-translate/parrot/web-app/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-57_binding.node
Download complete  ] - :
Binary saved to /home/soi/golang/src/github.com/parrot-translate/parrot/web-app/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /home/soi/.npm/node-sass/4.7.2/linux-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/soi/golang/src/github.com/parrot-translate/parrot/web-app/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.7.2 postinstall /home/soi/golang/src/github.com/parrot-translate/parrot/web-app/node_modules/node-sass
> node scripts/build.js

Binary found at /home/soi/golang/src/github.com/parrot-translate/parrot/web-app/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1177 packages in 28.017s
Building web app...

> parrot@0.0.0 build /home/soi/golang/src/github.com/parrot-translate/parrot/web-app
> ng build -prod

Date: 2018-02-11T14:32:42.796Z                                                          
Hash: 19044be6aceeeacf65a4
Time: 26306ms
chunk {0} polyfills.c29d11b006a5740ab391.bundle.js (polyfills) 100 kB [initial] [rendered]
chunk {1} styles.a4deb000d8b2b5071ddc.bundle.css (styles) 798 kB [initial] [rendered]
chunk {2} main.7cb3dbaa2302259a727f.bundle.js (main) 315 kB [initial] [rendered]
chunk {3} vendor.45d025b61882279ed3a6.bundle.js (vendor) 440 kB [initial] [rendered]
chunk {4} inline.544ee5f7618a2faefacb.bundle.js (inline) 1.45 kB [entry] [rendered]
Copying API sources to GOPATH workspace
cp: 无法获取'parrot-api' 的文件状态(stat): No such file or directory
[soi@master parrot]$ ls
[soi@master parrot]$ ll
总用量 0

```

## Steps to Reproduce the Problem

1. 
```
# From the root dir 'parrot'
$ ./build/build-all.sh
```
2.
3.

For feature suggestions please use the following template:

## Feature Suggestion
Your description...

**Comment by StanBoyet** [comment]
I have the same issue:

````bash
Installing web app dependencies, this might take a few minutes...
npm WARN codelyzer@3.0.1 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.

up to date in 5.391s
Building web app...

> parrot@0.0.0 build /Users/stan/dev/parrot/web-app
> ng build -prod

Date: 2018-04-25T09:36:07.883Z
Hash: a6c77b04519f19bef702
Time: 32144ms
chunk {0} polyfills.c29d11b006a5740ab391.bundle.js (polyfills) 100 kB [initial] [rendered]
chunk {1} styles.a4deb000d8b2b5071ddc.bundle.css (styles) 798 kB [initial] [rendered]
chunk {2} main.3918c4750f9356d7ef41.bundle.js (main) 315 kB [initial] [rendered]
chunk {3} vendor.45d025b61882279ed3a6.bundle.js (vendor) 440 kB [initial] [rendered]
chunk {4} inline.4c9227ef6e5096672878.bundle.js (inline) 1.45 kB [entry] [rendered]
Copying API sources to GOPATH workspace
Building Parrot API...
go get: no install location for directory /src/github.com/parrot-translate/parrot/parrot-api outside GOPATH
	For more details see: 'go help gopath'
go get: no install location for directory /src/github.com/parrot-translate/parrot/parrot-api/api outside GOPATH
	For more details see: 'go help gopath'
go get: no install location for directory /src/github.com/parrot-translate/parrot/parrot-api/auth outside GOPATH
	For more details see: 'go help gopath'
go get: no install location for directory /src/github.com/parrot-translate/parrot/parrot-api/config outside GOPATH
	For more details see: 'go help gopath'
go get: no install location for directory /src/github.com/parrot-translate/parrot/parrot-api/datastore outside GOPATH
	For more details see: 'go help gopath'
go get: no install location for directory /src/github.com/parrot-translate/parrot/parrot-api/datastore/errors outside GOPATH
	For more details see: 'go help gopath'
go get: no install location for directory /src/github.com/parrot-translate/parrot/parrot-api/datastore/postgres outside GOPATH
	For more details see: 'go help gopath'
go get: no install location for directory /src/github.com/parrot-translate/parrot/parrot-api/errors outside GOPATH
	For more details see: 'go help gopath'
go get: no install location for directory /src/github.com/parrot-translate/parrot/parrot-api/export outside GOPATH
	For more details see: 'go help gopath'
go get: no install location for directory /src/github.com/parrot-translate/parrot/parrot-api/logger outside GOPATH
	For more details see: 'go help gopath'
go get: no install location for directory /src/github.com/parrot-translate/parrot/parrot-api/model outside GOPATH
	For more details see: 'go help gopath'
go get: no install location for directory /src/github.com/parrot-translate/parrot/parrot-api/render outside GOPATH
	For more details see: 'go help gopath'
````

**Comment by ycrxun** [comment]
@StanBoyet You need to `export GOPATH`, such as:
```
$ export GOPATH=/home/soi/golang
# From the root dir 'parrot'
$ ./build/build-all.sh
```

**Comment by anthonynsimon** [comment]
This seems to be due to GOPATH not being set. You might want to add it to your shell profile. On the official Go docs you can find some more info on this: https://github.com/golang/go/wiki/SettingGOPATH

If it's ok with you guys, I'll be closing the issue. Feel free to open it again if it's still not a solution.

**Comment by ycrxun** [comment]
@anthonynsimon   My issuse is that I can't clone the project to my GOPATH, and keep the path `$GOPATH/src/github.com/parrot-translate/parrot`.
So,I need to clone the project out of my GOPATH.

**Comment by ycrxun** [comment]
```shell
$ echo $GOPATH
/home/soi/golang

$ go version
go version go1.10.1 linux/amd64
$ git clone https://github.com/parrot-translate/parrot.git $GOPATH/src/github.com/parrot-translate/parrot
$ cd $GOPATH/src/github.com/parrot-translate/parrot
$ pwd
/home/soi/golang/src/github.com/parrot-translate/parrot
$  ./build/build-all.sh
Installing web app dependencies, this might take a few minutes...

> node-sass@4.7.2 install /home/soi/golang/src/github.com/parrot-translate/parrot/web-app/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/soi/.npm/node-sass/4.7.2/linux-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/soi/golang/src/github.com/parrot-translate/parrot/web-app/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.7.2 postinstall /home/soi/golang/src/github.com/parrot-translate/parrot/web-app/node_modules/node-sass
> node scripts/build.js

Binary found at /home/soi/golang/src/github.com/parrot-translate/parrot/web-app/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1176 packages from 1227 contributors in 21.642s
Building web app...

> parrot@0.0.0 build /home/soi/golang/src/github.com/parrot-translate/parrot/web-app
> ng build -prod

Cannot find module 'ssri'
Error: Cannot find module 'ssri'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/soi/golang/src/github.com/parrot-translate/parrot/web-app/node_modules/cacache/lib/content/path.js:6:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/soi/golang/src/github.com/parrot-translate/parrot/web-app/node_modules/cacache/lib/entry-index.js:5:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! parrot@0.0.0 build: `ng build -prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parrot@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/soi/.npm/_logs/2018-05-24T08_24_29_246Z-debug.log
Copying API sources to GOPATH workspace
cp: 无法获取'parrot-api' 的文件状态(stat): No such file or directory
```
Then,I tried read the build script, I found `rm -rf $GO_WORKSPACE && mkdir -p $GO_WORKSPACE` in the `build-api.sh`.

**So,I understand that I can't clone into `$GOPATH/src/github.com/parrot-translate/parrot`,because of the path will be deleted during the build process.**

**Comment by anthonynsimon** [comment]
@ycrxun Thanks for the info! Yes I now see what you mean. Sorry for the inconvenience, at the moment the repo cannot be inside the GOPATH during build.

I will find a better solution, also with the recent announcement of [vgo](https://github.com/golang/go/issues/24301) for Go, it should make it easier to manage the workspaces, I will evaluate the options.

**Comment by anthonynsimon** [comment]
@ycrxun I removed the code that copies the Go sources to the GOPATH before building. You should now be able to build the project.

```bash
$ mkdir -p $GOPATH/src/github.com/parrot-translate/parrot
$ cd $GOPATH/src/github.com/parrot-translate/parrot
$ git clone https://github.com/parrot-translate/parrot.git .
$ build/build-all.sh
```

**Comment by ycrxun** [comment]
@anthonynsimon  It works as expected. :+1:
